---
# Build definition for Concourse.ci
platform: linux
image_resource:
  type: docker_image
  source:
    repository: golang

inputs:
  - name: terraform-provider-ansible

run:
  path: ./terraform-provider-ansible/ci/run-tests.sh
